#!/bin/bash
#Create branch
dir=$(dirname "$0")
copilotPATH=~/copilotDir
taskname=$(basename "$PWD")
taskDir="$copilotPATH/$taskname"

use_opencode=false
load_env=false
agentsEnv=".env4" # default environment
while getopts "oe:" opt; do
  case $opt in
    o)
      use_opencode=true
      ;;
    e)
      agentsEnv=".env$OPTARG" # e,g , -e 1 will set agentsEnv to .env1
      load_env=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [ -d "$copilotPATH/$agentsEnv" ]; then
    agentsEnv="$agentsEnv"
elif [ -d "$copilotPATH/.env3" ]; then
    agentsEnv=".env3"
elif [ -d "$copilotPATH/.env2" ]; then
    agentsEnv=".env2"
elif [ -d "$copilotPATH/.env1" ]; then
    agentsEnv=".env1"
fi

echo "agents environment : $agentsEnv"
echo "task Name : $taskname"
echo "issue directory : $taskDir"
echo "use OpenCode : $use_opencode"
# remove previous copilot data if exists
if [ -d "$taskDir/.github" ]; then
    rm -rf "$taskDir/.github"
fi
if [ -d "$taskDir/.copilot" ]; then
    rm -rf "$taskDir/.copilot"
fi
# Copy files
if [ -d "$copilotPATH/.vscode" ]; then
    cp -r "$copilotPATH/.vscode" "$taskDir/"
fi
mkdir -p "$taskDir/.github"
mkdir -p "$taskDir/.logs"
if [ -d "$copilotPATH/$agentsEnv" ]; then
    cp -r "$copilotPATH/$agentsEnv"/* "$taskDir/.github"
fi
# Create the .opencode directory if it doesn't exist
mkdir -p .opencode

# Symlink your github skills and agents into OpenCode's native path
ln -s ../.github/skills .opencode/skills
ln -s ../.github/agents .opencode/agents

if [ "$use_opencode" = true ]; then
    opencode \
     --prompt "skill(orchestrator)" \
     --agent Orchestrator \
     --port 4030 
else

# run copilot 
# session_id=$(timeout 1s copilot -r $session_id -p "/session id" 2>/dev/null | tail -n 1)
# echo "session id : $session_id"
# if [ -n "$session_id" ]; then
#     copilot \
#         -C "$taskDir" \
#         -i "start" \
#         --resume="$taskname" \
#         --allow-all \
#         --agent Orchestrator \
#         --log-dir "$taskDir/.logs" 
# else
copilot \
    -C "$taskDir" \
    -i "skill(orchestrator)" \
    --name="$taskname" \
    --allow-all \
    --log-dir "$taskDir/.logs" \
    --agent Orchestrator
# fi
fi