#!/bin/bash
dir=$(dirname "$0")
. $dir/getEnv.sh

case "$APP_TYPE" in
  node)
        echo "Detected Node.js application"
        ENTRYPOINT=$(npm pkg get bin | jq -r)
        echo "APPNAME : $(npm pkg get name | jq -r)"
        echo "ENTRYPOINT : $ENTRYPOINT"
        npx ncc build ${ENTRYPOINT}  -m -o ./.dist
        assets
        echo "node \$0/../index.js" > ./.dist/run.sh
        chmod 777 ./.dist/run.sh
    ;;
  dotnet)
    echo "Detected .NET application"
    dotnet publish -c Release -o ./.dist
    echo "dotnet run" > ./.dist/run.sh
    chmod 777 ./.dist/run.sh
    ;;
  angular)
    echo "Detected Angular application"
    ng build --configuration=production --output-path=./.dist
    ;;
  *)
    echo "No application type detected. Defaulting to 'unknown'."
    ;;
esac