#!/usr/bin/env node
import pkg from `${process.cwd()}/package.json`;

const { assets } = pkg;
const all = [...assets.files,...assets.folders];
for (const {source, destination} of all) {
    console.log(`COPY --from=build /app/${source} ${destination}`);
}
