

# Production stage
FROM node:20-alpine AS production
ARG APP_NAME
ARG APP_VERSION
ARG TAG
WORKDIR /app
# Copy the built site from the build stage
COPY . ./

ENV APP_NAME=$APP_NAME

# ENV APP_NAME=$APP_NAME
ENV APP_VERSION=$APP_VERSION
ENV TAG=$TAG
ENV PORT=8080
ENV ACTUATOR_PORT=9090

# Expose the application port
EXPOSE 8080
# Expose the application actuator port
EXPOSE 9090

LABEL full_tag=$TAG
LABEL app_name=$APP_NAME
LABEL app_version=$APP_VERSION
LABEL namespace="csp"
LABEL build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

CMD ["sh", "-c", "echo '{}' > ./app/config/env.json"]

ENTRYPOINT ["sh", "/app/run.sh"]
