#!/bin/bash
#create pull request
# Get the git origin URL
ORIGIN_URL=$(git config --get remote.origin.url)

# Convert SSH URL to HTTPS if needed
if [[ $ORIGIN_URL == git@* ]]; then
    ORIGIN_URL=${ORIGIN_URL#git@}
    ORIGIN_URL="https://${ORIGIN_URL/:/\/}"
fi

# Add /pull/new if it ends with .git
if [[ $ORIGIN_URL == *.git ]]; then
    ORIGIN_URL=${ORIGIN_URL%.git}/pull-requests/new
else
    ORIGIN_URL=$ORIGIN_URL/pull-requests/new
fi

echo "Opening pull request at: $ORIGIN_URL"
# Open the URL in the default web browser
branch=$(git branch --show-current)
open "$ORIGIN_URL?source=$branch&destination=master"