#!/bin/bash
#Create branch
set -e
dir=$(dirname "$0")
workspace=~/workspace
issueurl=$1 # Branch name from the first argument e.g https://contellect.atlassian.net/browse/CON-7802
taskname=$issueurl
if [[ $issueurl == http* ]]; then
    taskname=${issueurl##*/} # Extract branch name after the last /
fi

taskDir="$workspace/$taskname"
echo "issue url : $issueurl"
echo "task Name : $taskname"
echo "issue directory : $taskDir"

# 2. Create the folder if it does not exist for issue `./<issue_name>` . (edit tool)
if [ ! -d "$taskDir" ]; then
    mkdir -p "$taskDir"
fi
# run zed
zed $taskDir
